# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    tags:
      - 'v*'

name: Build & Release

jobs:
  aps-viewer-visual:
    name: Build Viewer Visual
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./visuals/aps-viewer-visual
        run: npm ci && npm install -g powerbi-visuals-tools
      - name: Build
        working-directory: ./visuals/aps-viewer-visual
        run: npm run package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aps-viewer-visual
          path: ./visuals/aps-viewer-visual/dist/*.pbiviz
  create-release:
    name: Create New Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [aps-viewer-visual]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: Roang-zero1/github-create-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v3
        with:
          args: "aps-viewer-visual/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}